Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
all_metadata = dataset.data.metadata()
assert len(all_metadata) > 0, "No pieces selected for analysis."
print(f"Concatenated 'metadata.tsv' files cover {len(all_metadata)} of the {dataset.data.count_pieces()} scores.")
all_metadata.reset_index(level=1).groupby(level=0).nth(0).iloc[:,:20]
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
Cell [0;32mIn[7], line 2[0m
[1;32m      1[0m all_metadata [38;5;241m=[39m dataset[38;5;241m.[39mdata[38;5;241m.[39mmetadata()
[0;32m----> 2[0m [38;5;28;01massert[39;00m [38;5;28mlen[39m(all_metadata) [38;5;241m>[39m [38;5;241m0[39m, [38;5;124m"[39m[38;5;124mNo pieces selected for analysis.[39m[38;5;124m"[39m
[1;32m      3[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mConcatenated [39m[38;5;124m'[39m[38;5;124mmetadata.tsv[39m[38;5;124m'[39m[38;5;124m files cover [39m[38;5;132;01m{[39;00m[38;5;28mlen[39m(all_metadata)[38;5;132;01m}[39;00m[38;5;124m of the [39m[38;5;132;01m{[39;00mdataset[38;5;241m.[39mdata[38;5;241m.[39mcount_pieces()[38;5;132;01m}[39;00m[38;5;124m scores.[39m[38;5;124m"[39m)
[1;32m      4[0m all_metadata[38;5;241m.[39mreset_index(level[38;5;241m=[39m[38;5;241m1[39m)[38;5;241m.[39mgroupby(level[38;5;241m=[39m[38;5;241m0[39m)[38;5;241m.[39mnth([38;5;241m0[39m)[38;5;241m.[39miloc[:,:[38;5;241m20[39m]

[0;31mAssertionError[0m: No pieces selected for analysis.
AssertionError: No pieces selected for analysis.

